In [ ]:
# Q01. What is a Python library? Why do we use Python libraries?

# A Python library is a collection of pre-written code for specific tasks.
# We use Python libraries to save time,access specialized functionalities (like data analysis or machine learning),
# leverage community contributions, ensure reliability, and scale projects effectively.
# They help developers work more efficiently and build powerful applications by reusing existing code and resources.

In [ ]:
# Q02. What is the difference between Numpy array and List?

# The main differences between NumPy arrays and Python lists are:

# 1. **Data Type and Homogeneity**:
#    - NumPy arrays are homogeneous, meaning they contain elements of the same data type. This allows for more efficient storage and operations.
#    - Python lists can contain elements of different data types and are heterogeneous.

# 2. **Performance**:
#    - NumPy arrays are optimized for numerical operations and are generally faster and more memory efficient than Python lists, especially for large datasets.
#    - Python lists are more flexible but tend to be slower for numerical computations due to their dynamic nature.

# 3. **Functionality**:
#    - NumPy arrays offer a wide range of mathematical functions and operations for array manipulation, linear algebra, Fourier transforms, and more.
#    - Python lists have a more general-purpose nature and offer basic operations for list manipulation but lack the specialized functions available in NumPy.

# 4. **Memory Overhead**:
#    - NumPy arrays have less memory overhead compared to Python lists because they store data in contiguous memory blocks.
#    - Python lists have additional memory overhead due to the overhead of storing type information and references to objects.

# In summary, NumPy arrays are better suited for numerical computations and large datasets due to their homogeneity, performance, and specialized functionality.
# Python lists, on the other hand, offer more flexibility and are suitable for general-purpose data storage and manipulation when performance is not a critical factor.



In [1]:
# Q3 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]


import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("Shape:", array.shape) # (3,4)
print("Size:", array.size) # 12
print("Dimension:", array.ndim) #2


Shape: (3, 4)
Size: 12
Dimension: 2


In [3]:
# Q4. 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print("fisrt row of the array is:",array[0])

fisrt row of the array is: [1 2 3 4]


In [5]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
element = array[2][3]
print("Element at the third row and fourth column in the array is:",element)


Element at the third row and fourth column in the array is: 12


In [ ]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# using for loop
for row in range(len(array)):
  for column in range(len(array[row])):
    if column % 2 != 0:
      print(array[row][column])

# using array slicing
odd_indexed_elements = array[:, 1::2]
print(odd_indexed_elements)

In [18]:
# Q7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np

random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:")
print(random_matrix)


Random 3x3 Matrix:
[[ 0.04458389  1.18778862  0.1702829 ]
 [-0.56900229  0.8699479   0.37555547]
 [-0.9897486  -1.67991548 -0.18597849]]


In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# `np.random.rand` and `np.random.randn` are both functions provided by NumPy for generating random numbers, but they differ in the way they generate these numbers and the distributions they sample from.

# 1. **`np.random.rand`:**
#    - `np.random.rand` generates random numbers from a uniform distribution over the range [0, 1].
#    - It takes dimensions as input and returns an array of random numbers with the specified shape.
#    - Each value in the array is sampled independently and uniformly from the [0, 1) interval.
#    - Example: `np.random.rand(3, 3)` generates a 3x3 array of random numbers between 0 and 1.

# 2. **`np.random.randn`:**
#    - `np.random.randn` generates random numbers from a standard normal distribution (mean 0, standard deviation 1).
#    - It takes dimensions as input and returns an array of random numbers with the specified shape.
#    - The values are sampled from a Gaussian distribution centered around 0 with a standard deviation of 1.
#    - It produces values that are more likely to be close to 0 and less likely to be far away from 0, following the bell curve of the normal distribution.
#    - Example: `np.random.randn(3, 3)` generates a 3x3 array of random numbers sampled from a standard normal distribution.

# In summary, `np.random.rand` samples from a uniform distribution over the range [0, 1),
# while `np.random.randn` samples from a standard normal distribution with mean 0 and standard deviation 1.
# The choice between the two depends on the specific requirements of your application and the desired distribution of random numbers.

In [ ]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Increase the dimension of the array
expanded_array_axis0 = np.expand_dims(array, axis=0)  # Add a new dimension at axis 0

print("Original Array:")
print(array)
print("\nArray with Increased Dimension:")
print(expanded_array_axis0)


In [29]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]


import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

transposed_array = np.transpose(array)

print("Original Array:")
print(array)
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [32]:
# 11. Consider the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python:
# 1.Index wise multiplication
# 2.Matrix multiplication
# 3.Add both the matrics
# 4.Subtract matrix B from A
# 5.Divide Matrix B by A


import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# 1.Index wise multiplication
result = A2 * B2
print("Result of Index-wise Multiplication:")
print(result)

# 2.Matrix multiplication
result = A2 @ B2.T
print("Result of Matrix Multiplication:")
print(result)

# 3.Add both the matrics
result = A2 + B2
print("Result of Matrix Addition:")
print(result)

# 4.Subtract matrix B from A
result = B2 - A2
print("Result of Matrix Subtraction:")
print(result)

# 5.Divide Matrix B by A
result = B2 / A2
print("Result of Matrix Division (B / A):")
print(result)

Result of Index-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Result of Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Result of Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Result of Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Result of Matrix Division (B / A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
# 12.  Which function in Numpy can be used to swap the byte order of an array?

# In NumPy, the function np.ndarray.byteswap() can be used to swap the byte order of an array. This function swaps the byte order of the elements in the array in place.
import numpy as np

# Define an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)
print("Before Swapped Array:", arr)
# Swap the byte order of the array
arr  = arr.byteswap(True)
print("Swapped Array:", arr)
# the byte order of the arr array is swapped. The True argument in the byteswap() function call indicates that the byte order should be swapped in place.
# The byte order is swapped for the elements of the array according to the specified data type.

Before Swapped Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


In [ ]:
# 13.  What is the significance of the np.linalg.inv function?
# The np.linalg.inv() function in NumPy computes the multiplicative inverse of a square matrix.
# It's used for solving systems of linear equations, calculating eigenvalues and eigenvectors, and performing various matrix operations.
# The matrix must be square and non-singular for the function to compute a valid inverse.

In [ ]:
# 14. What does the np.reshape function do, and how is it used?
# The np.reshape() function in NumPy is used to change the shape (dimensions) of an array without changing its data.
# It allows you to rearrange the elements of the array to fit into a new shape specified by the dimensions you provide.
# Here's how np.reshape() works:

# Changing Shape: You provide the desired shape as a tuple of integers to the np.reshape() function.
#                 The total number of elements in the original array must match the total number of elements in the new shape.

# Rearranging Elements: The function rearranges the elements of the array to fit into the new shape while maintaining the order of elements.

# In-place Operation: The np.reshape() function returns a new view of the original array with the specified shape.
#                     It does not modify the original array but provides a different view of it with the desired shape.

import numpy as np

# Define an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print("Original Array:")
print(arr)
print("\nReshaped Array:")
print(reshaped_arr)




In [39]:
# 15. What is broadcasting in Numpy?

# Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined together in arithmetic operations.
# It enables NumPy to perform element-wise operations on arrays even if their shapes are not identical,
# by implicitly expanding the smaller arrays to match the shape of the larger array.

# The key concepts of broadcasting in NumPy are:
# Shape Compatibility: Arrays can be broadcast together if their shapes are compatible. Two dimensions are compatible when they are equal, or one of them is 1.
# Implicit Expansion: NumPy automatically expands the smaller array along the missing dimensions to match the shape of the larger array during arithmetic operations.
# Efficiency: Broadcasting enables vectorized operations, avoiding the need for explicit looping through array elements, which leads to more concise and efficient code.

# Here's a simple example to illustrate broadcasting in NumPy:
import numpy as np

# Create a 3x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Create a 1D array
arr2 = np.array([1, 0, -1])

# Add the 1D array to each row of the 2D array
result = arr1 + arr2
print(result)

# [[ 2  2  2]
#  [ 5  5  5]
#  [ 8  8  8]]

# the 1D array arr2 is broadcasted to match the shape of the 2D array arr1. The array arr2 is implicitly expanded along the rows to become:
# [[1, 0, -1],
#  [1, 0, -1],
#  [1, 0, -1]]

# Then, element-wise addition is performed between arr1 and the expanded arr2.
# This broadcasting operation allows us to add a 1D array to a 2D array without explicitly duplicating the 1D array along the rows.
# Broadcasting simplifies the syntax and makes code more readable and efficient.

[[2 2 2]
 [5 5 5]
 [8 8 8]]
