In [1]:
from sklearn.datasets import load_iris # get the iris data set
data = load_iris()

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target # in binary classification problem we have filtered one to keep only 2 classes
df.target.unique()

array([0, 1, 2])

In [4]:
X = df.iloc[:, :-1]
y= df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=1)

In [6]:
from sklearn.linear_model import LogisticRegression # use logistic regression model as this is a classification problem
classifier = LogisticRegression(max_iter=300) 
# max_iter = This will ensure that the logistic regression model has enough iterations to converge, especially useful for complex datasets.
classifier

LogisticRegression(max_iter=300)

In [7]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=300)

In [8]:
y_pred = classifier.predict(X_test)
y_pred 

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [9]:
classifier.predict_proba(X_test) # below is showing the probability of all 3 classes

array([[9.84781495e-01, 1.52184836e-02, 2.17021885e-08],
       [2.75652449e-01, 7.21699475e-01, 2.64807598e-03],
       [6.30966867e-03, 8.89224661e-01, 1.04465671e-01],
       [9.85534799e-01, 1.44651381e-02, 6.32758546e-08],
       [1.19482712e-06, 1.90211836e-02, 9.80977622e-01],
       [4.54554478e-03, 6.27707600e-01, 3.67746855e-01],
       [1.47964166e-04, 1.27857258e-01, 8.71994778e-01],
       [9.57878304e-01, 4.21204682e-02, 1.22792236e-06],
       [9.69543309e-01, 3.04563808e-02, 3.09781493e-07],
       [9.81758661e-06, 2.70734782e-02, 9.72916704e-01],
       [1.90062325e-02, 8.79690963e-01, 1.01302805e-01],
       [9.66563549e-01, 3.34360089e-02, 4.41873809e-07],
       [4.75488912e-06, 3.10385320e-02, 9.68956713e-01],
       [7.17823553e-03, 8.01770059e-01, 1.91051705e-01],
       [6.99724407e-03, 7.49119953e-01, 2.43882802e-01],
       [9.88083204e-01, 1.19167290e-02, 6.73609424e-08],
       [2.25389205e-02, 9.36972940e-01, 4.04881396e-02],
       [1.09763656e-02, 6.81642

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [11]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



ROC AUC curve for model
will not be calculated as this is muliclass classification