In [ ]:
#https://www.w3resource.com/python-exercises/numpy/index-array.php

In [2]:
import numpy as np #2005 by Travis Oliphant

In [ ]:
np.__version__

In [ ]:
print(np.__doc__)

In [ ]:
#Why numpy
#-mathematical function
#Faster

In [ ]:
l = [1, 2, 3, 4, 5]
arr1 = np.array(l)
print(arr1)
type(arr1)

In [ ]:
l = [1, 2, 3, 4, 5, "Rishi"]
arr1 = np.array(l)
print(arr1)
type(arr1)

In [ ]:
arr1.ndim

In [ ]:
arr1 = np.array([[[[1, 2, 3], [4, 5, 6] , [7, 8, 9]]]])

In [ ]:
arr1

In [ ]:
arr1.ndim

In [ ]:
l = [1, 2, 3, 4]

In [ ]:
np.array(l)

In [ ]:
mat = np.matrix(l) #matrix will be by default 2d

In [ ]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])

In [ ]:
arr1 = np.array([[[1, 2], [5, 6], [7, 8]]])

In [ ]:
arr1.ndim

In [ ]:
#more way to convert to array
np.asarray([[[1, 2], [5, 6], [7, 8]]])

In [ ]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.

In [ ]:
mat

In [ ]:
np.asanyarray(mat)

In [ ]:
np.asarray(mat)

In [ ]:
np.asarray([[[1, 2], [5, 6], [7, 8]]])

In [ ]:
np.array([[[1, 2], [5, 6], [7, 8]]])

In [ ]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

In [ ]:
np.array(t)

In [ ]:
a = 5
np.array(a)

In [ ]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

In [ ]:
a = arr

In [ ]:
a

In [ ]:
arr[0] = 1000

In [ ]:
arr

In [ ]:
a

In [ ]:
a

In [ ]:
b = a.copy()
b[0] = 2000

In [ ]:
b

In [ ]:
a

In [ ]:
#to create array >> .array, .asasrray, .asanyarray, deep copy, shallow copy

In [ ]:
#There are multiple ways to generating arrays

In [41]:
np.fromfunction(lambda i, j : i==j, shape=(3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
arr1

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [44]:
arr1.shape

(1, 3, 2)

In [46]:
arr1.size

6

In [ ]:
arr1.shape

In [ ]:
arr.size

In [ ]:
arr1.size

In [ ]:
np.fromfunction(lambda i, j : i==j, (3, 3))

In [47]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
for i in range(5):
    print(i)

In [ ]:
[i for i in range(5)]

In [ ]:
list(i for i in range(5))

In [ ]:
list(range(5))

In [48]:
iterable = (i*i for i in range(5))

In [49]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [55]:
np.fromstring('233.467.5676', sep = '.')

array([ 233.467, 5676.   ])

In [58]:
np.fromstring('23,34,67', sep = ',', dtype=int)

array([23, 34, 67])

In [59]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',',dtype=string)

NameError: name 'string' is not defined

In [ ]:
arr

In [ ]:
arr.size

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
l = [1, 2,3, "Ajay"]
arr = np.array(l)
arr.dtype

In [ ]:
arr

In [ ]:
list(range(5))

In [ ]:
range(5)

In [ ]:
list(range(1.0, 2.10))

In [67]:
np.arange(1, 5, -.9)

array([], dtype=float64)

In [64]:
list(np.arange(1, 5, 1))

[1, 2, 3, 4]

In [68]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [69]:
np.logspace(1, 5, 10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [70]:
np.logspace(1, 5, 10, base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [71]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [ ]:
arr1

In [ ]:
arr1.ndim

In [77]:
arr2 = np.zeros((3, 4),dtype=int)
print(arr2)
arr2.shape

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


(3, 4)

In [ ]:
arr2

In [ ]:
arr2.ndim

In [89]:
arr3 = np.zeros((1,3,4))
print(arr3)
arr3.shape

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


(1, 3, 4)

In [90]:
arr3.ndim

3

In [7]:
arr4 = np.zeros((1,1, 3, 4))
print(arr4[0][0][0])
arr4.shape

[0. 0. 0. 0.]


(1, 1, 3, 4)

In [94]:
arr4.ndim

3

In [ ]:
arr4

In [ ]:
np.ones(5)

In [95]:
arr = np.ones((3,4))

In [96]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [98]:
arr * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [104]:
arr7 = np.array([[[[[[[[[[[[[[1, 1, 1, 1]]]]]]]]]]]]]])
print(arr7)
print(arr7.ndim)

arr7.shape

[[[[[[[[[[[[[[1 1 1 1]]]]]]]]]]]]]]
14


(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)

In [ ]:
np.twos((2,3))

In [ ]:
l = [1, 2,3, 4,5, "Prince"]
arr = np.array(l)
arr.dtype

In [ ]:
arr

In [8]:
arr8 = np.array(["v",1,2,3])

In [9]:
arr8

array(['v', '1', '2', '3'], dtype='<U11')

In [10]:
arr8.dtype

dtype('<U11')

In [12]:
type(arr8[1])

numpy.str_