In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
np.random.seed(1)

In [15]:
X = 2*np.random.rand(100,1)
X

array([[8.34044009e-01],
       [1.44064899e+00],
       [2.28749635e-04],
       [6.04665145e-01],
       [2.93511782e-01],
       [1.84677190e-01],
       [3.72520423e-01],
       [6.91121454e-01],
       [7.93534948e-01],
       [1.07763347e+00],
       [8.38389029e-01],
       [1.37043900e+00],
       [4.08904499e-01],
       [1.75623487e+00],
       [5.47751864e-02],
       [1.34093502e+00],
       [8.34609605e-01],
       [1.11737966e+00],
       [2.80773877e-01],
       [3.96202978e-01],
       [1.60148914e+00],
       [1.93652315e+00],
       [6.26848356e-01],
       [1.38464523e+00],
       [1.75277830e+00],
       [1.78921333e+00],
       [1.70088423e-01],
       [7.81095665e-02],
       [3.39660839e-01],
       [1.75628501e+00],
       [1.96693668e-01],
       [8.42215250e-01],
       [1.91577906e+00],
       [1.06633057e+00],
       [1.38375423e+00],
       [6.31031262e-01],
       [1.37300186e+00],
       [1.66925134e+00],
       [3.65765547e-02],
       [1.50028863e+00],


In [16]:
y = 4+ 3*X + 1.5*X**2 +np.random.rand(100,1)
y

array([[ 7.87222104],
       [11.96220932],
       [ 4.88662843],
       [ 6.7196951 ],
       [ 5.91829424],
       [ 5.22855018],
       [ 5.34153971],
       [ 7.71927489],
       [ 8.01604833],
       [ 9.97216409],
       [ 7.74185184],
       [11.06560733],
       [ 6.4101133 ],
       [14.59206417],
       [ 4.23482621],
       [11.47542821],
       [ 8.30256479],
       [10.14796945],
       [ 5.67209735],
       [ 5.5483451 ],
       [12.67149873],
       [15.46096332],
       [ 6.49825985],
       [11.27601039],
       [14.72671054],
       [14.70839754],
       [ 5.10648235],
       [ 5.08551125],
       [ 5.31621006],
       [14.17484424],
       [ 5.23387287],
       [ 8.56023129],
       [15.81368151],
       [ 8.92323033],
       [11.824059  ],
       [ 6.72336874],
       [11.7538119 ],
       [13.57521475],
       [ 4.97527829],
       [12.62428649],
       [16.35648429],
       [11.98396023],
       [ 6.21447464],
       [12.59479058],
       [ 4.72784157],
       [ 7

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_tets,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [18]:
from sklearn.preprocessing import PolynomialFeatures

ploy_feature = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = ploy_feature.fit_transform(X_train)

In [19]:
X_train_poly

array([[2.28749635e-04, 5.23263954e-08],
       [1.61478258e+00, 2.60752277e+00],
       [1.14735897e+00, 1.31643261e+00],
       [1.38880032e+00, 1.92876632e+00],
       [3.96202978e-01, 1.56976800e-01],
       [6.31031262e-01, 3.98200454e-01],
       [8.16273606e-01, 6.66302599e-01],
       [7.81095665e-02, 6.10110437e-03],
       [1.81719101e+00, 3.30218315e+00],
       [3.65765547e-02, 1.33784435e-03],
       [1.02977822e+00, 1.06044319e+00],
       [1.23428983e+00, 1.52347138e+00],
       [9.83146319e-01, 9.66576684e-01],
       [4.74053960e-01, 2.24727157e-01],
       [1.32688300e+00, 1.76061848e+00],
       [1.97772218e+00, 3.91138501e+00],
       [5.75550677e-01, 3.31258582e-01],
       [1.39951672e+00, 1.95864705e+00],
       [1.38464523e+00, 1.91724242e+00],
       [1.38375423e+00, 1.91477576e+00],
       [8.56182380e-01, 7.33048267e-01],
       [5.31093319e-01, 2.82060113e-01],
       [6.95531719e-01, 4.83764373e-01],
       [1.34093502e+00, 1.79810673e+00],
       [6.977966

In [21]:
from sklearn.linear_model import LinearRegression
poly_reg = LinearRegression()
poly_reg

LinearRegression()

In [22]:
poly_reg.fit(X_train_poly,y_train)

LinearRegression()

In [24]:
poly_reg.coef_

array([[3.04129232, 1.45703431]])

In [26]:
poly_reg.intercept_

array([4.49641468])

In [ ]:
y_pred= 