In [1]:
 # data encoding >> converting categorical column to numeric values
# Nominal/OHE
#label and ordinal encoding
# target guided ordinal encoding 

In [2]:
# nominal/ OHE >> binary (0,1) vectors for each category , creating dummy variables which is qual to n-1

In [3]:
# single, married, in a relationship
# single > [1,0,0]
# married > [0,1,0]
# separated > [0,0,1]

In [4]:
import pandas as pd


In [6]:
df = pd.DataFrame({'status':['Single','Married','Single','Relationship','Married','Single']})

In [7]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [16]:
# dummy variables with pd
one_hot_encoded = pd.get_dummies(df,columns=['status'])

In [17]:
one_hot_encoded

status_Married  status_Relationship  status_Single
0           False                False           True
1            True                False          False
2           False                False           True
3           False                 True          False
4            True                False          False
5           False                False           True

In [18]:

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoder

OneHotEncoder()

In [19]:
encoder.fit(df[['status']])

OneHotEncoder()

In [20]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [21]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [22]:
encoder.get_feature_names_out()

array(['status_Married', 'status_Relationship', 'status_Single'],
      dtype=object)

In [26]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out()) # data set with dummy values

In [24]:
 # new data coming in data set after doing the encoding we will use transform
# EX for status as 'Single'

encoder.transform([['Single']]).toarray()


C:\Users\avina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [25]:
# EX for status as 'Married'
encoder.transform([['Married']]).toarray()


C:\Users\avina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [35]:
final_df = pd.concat([df,encoder_df], axis=1)

In [36]:
final_df # there are redundant column below we can drop 2 columns which can still be able to explain data set

status  status_Married  status_Relationship  status_Single
0        Single             0.0                  0.0            1.0
1       Married             1.0                  0.0            0.0
2        Single             0.0                  0.0            1.0
3  Relationship             0.0                  1.0            0.0
4       Married             1.0                  0.0            0.0
5        Single             0.0                  0.0            1.0

In [33]:
final_df.drop(['status','status_Single'],axis=1, inplace=True)

In [34]:
final_df

status_Married  status_Relationship
0             0.0                  0.0
1             1.0                  0.0
2             0.0                  0.0
3             0.0                  1.0
4             1.0                  0.0
5             0.0                  0.0

In [39]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [40]:
# pandas get dummies 
one_hot_encoded = pd.get_dummies(df,columns=['status'], drop_first=True, dtype='int') 
# drop_first=True will drop the first column that was status_Married
# dtype int will make true and false to zero and one

In [41]:
one_hot_encoded

status_Relationship  status_Single
0                    0              1
1                    0              0
2                    0              1
3                    1              0
4                    0              0
5                    0              1

In [42]:
# internal homework

import seaborn as sns
sns.load_dataset('tips')

# perform one hot encoding on day column

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [43]:
# next encoding >> Label encoding  >> putting an unique integer for each categorical value 
# example : Single  as 0 , Married as 1, relationship  as 2

df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
labelEncoder =  LabelEncoder()

In [46]:
labelEncoder

LabelEncoder()

In [47]:
labelEncoder.fit_transform(df[['status']])

C:\Users\avina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 1, 0, 2])

In [48]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [49]:
# due to numbering it may be chance the ML model treat this as ranking or some sort of relationship
# for this we need to use ordinal encoder

# ordinal encoding

# high school(HS) >>1
#graduate(GR) >> 2
#pg >> 3
#phd >> 4

In [50]:
from sklearn.preprocessing import OrdinalEncoder

In [60]:
df = pd.DataFrame({"qualification":['HS','PG','GR','HS','PhD','HS','PG']})

In [61]:
df['qualification']

0     HS
1     PG
2     GR
3     HS
4    PhD
5     HS
6     PG
Name: qualification, dtype: object

In [56]:
encoder = OrdinalEncoder(categories=[["HS","GR","PG","PhD"]]) # this is the order user is defining

In [57]:
encoder

OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PhD']])

In [62]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [2.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.]])

In [63]:
df

qualification
0            HS
1            PG
2            GR
3            HS
4           PhD
5            HS
6            PG

In [64]:
# Top 5/10 >> at least 70 or 80 percent of the categorical column captured

df.qualification.value_counts()

qualification
HS     3
PG     2
GR     1
PhD    1
Name: count, dtype: int64

In [67]:
# Target guided ordinal encoding on top of label/ordinal encoding
# relationship along with target variable
# when to use when lot of unique categories
# replace with mean and median

df = pd.DataFrame({'time':['lunch','breakfast','dinner','lunch','breakfast','dinner','lunch','breakfast','dinner'],
              'total_bill':[120,120,40,150,160,120,120,40,150]})

In [68]:
df

time  total_bill
0      lunch         120
1  breakfast         120
2     dinner          40
3      lunch         150
4  breakfast         160
5     dinner         120
6      lunch         120
7  breakfast          40
8     dinner         150

In [69]:
mean_price = df.groupby('time')['total_bill'].mean()

In [70]:
mean_price

time
breakfast    106.666667
dinner       103.333333
lunch        130.000000
Name: total_bill, dtype: float64

In [71]:
df['time_target_encoded'] = df['time'].map(mean_price)

In [72]:
df

time  total_bill  time_target_encoded
0      lunch         120           130.000000
1  breakfast         120           106.666667
2     dinner          40           103.333333
3      lunch         150           130.000000
4  breakfast         160           106.666667
5     dinner         120           103.333333
6      lunch         120           130.000000
7  breakfast          40           106.666667
8     dinner         150           103.333333

In [73]:
# using sns use tips data set for target encoding
import seaborn as sns

In [75]:
data_set = sns.load_dataset('tips')
data_set

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [83]:
# target encoding 
mean_bill = data_set.groupby('time')['total_bill'].mean()

C:\Users\avina\AppData\Local\Temp\ipykernel_4888\695279989.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = data_set.groupby('time')['total_bill'].mean()


In [84]:
mean_bill

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [85]:
data_set['time_target_encoded'] = data_set.time.map(mean_bill)

In [86]:
data_set

total_bill   tip     sex smoker   day    time  size time_target_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2           20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3           20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3           20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2           20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4           20.797159
..          ...   ...     ...    ...   ...     ...   ...                 ...
239       29.03  5.92    Male     No   Sat  Dinner     3           20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2           20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2           20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2           20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2           20.797159

[244 rows x 8 columns]