In [ ]:
import numpy as np

In [ ]:
data = np.array([[[1],[2],[3]]])

In [ ]:
data

In [ ]:
data.ndim

In [ ]:
a = np.squeeze(data) # reduce the dimension by one

In [ ]:
a.ndim

In [ ]:
a = np.squeeze(a)

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
b = np.array([[1,2],[3,4]])

In [ ]:
b

In [ ]:
b_reshape = np.repeat(b,2)
b_reshape.size
b_reshape

In [ ]:
b_reshape.reshape((4,2))
#b

In [ ]:
np.repeat(b,2,axis=1) # axis 1 is column wise

In [ ]:
np.repeat(b,2,axis=0) # axis 0 is row wise

In [ ]:
data

In [ ]:
np.roll(data,3)

In [ ]:
b

In [ ]:
np.roll(b,1,axis=0)

In [ ]:
np.diag(np.array([1,2,3,4]))
# Extracting Diagonal Elements: When given a 2D array, numpy.diag() can extract the diagonal elements and return them as a 1D array.
# Constructing Diagonal Arrays: When given a 1D array, numpy.diag() can construct a 2D array with the input array as its diagonal elements 
# and zeros elsewhere.

In [ ]:
# Extract Diagonal Elements:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(np.diag(arr))  # Output: [1 5 9]

In [ ]:
# Construct Diagonal Array:
v = np.array([1, 2, 3])
print(np.diag(np.array([1, 2, 3])))

In [51]:
# binary operation an array

In [52]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [53]:
arr1

array([[7, 5, 4, 9],
       [7, 4, 7, 9],
       [8, 9, 9, 4]])

In [54]:
arr2

array([[2, 4, 4, 2],
       [9, 2, 2, 8],
       [6, 7, 4, 5]])

In [55]:
arr1+arr2

array([[ 9,  9,  8, 11],
       [16,  6,  9, 17],
       [14, 16, 13,  9]])

In [56]:
arr1*arr2

array([[14, 20, 16, 18],
       [63,  8, 14, 72],
       [48, 63, 36, 20]])

In [57]:
arr1**arr2

array([[      49,      625,      256,       81],
       [40353607,       16,       49, 43046721],
       [  262144,  4782969,     6561,     1024]])

In [58]:
arr1 >arr2

array([[ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [59]:
~arr1 # takes the positive number in negative axis and -1 added to that Ex: 2 will become -3

array([[ -8,  -6,  -5, -10],
       [ -8,  -5,  -8, -10],
       [ -9, -10, -10,  -5]])

In [60]:
arr1

array([[7, 5, 4, 9],
       [7, 4, 7, 9],
       [8, 9, 9, 4]])

In [61]:
# numpy string functions

In [78]:
arr = np.array(["pw skills","avinash rai"])
arr

array(['pw skills', 'avinash rai'], dtype='<U11')

In [79]:
np.char.upper(arr)

array(['PW SKILLS', 'AVINASH RAI'], dtype='<U11')

In [80]:
np.char.upper(np.array(["Avi"]))

array(['AVI'], dtype='<U3')

In [81]:
np.char.capitalize(arr) # only capitalizes the first letter of each element.

array(['Pw skills', 'Avinash rai'], dtype='<U11')

In [82]:
np.char.title(arr) # capitalizes the first letter of each word in each element of the array.

array(['Pw Skills', 'Avinash Rai'], dtype='<U11')

In [70]:
# mathematical function
arr1

array([[7, 5, 4, 9],
       [7, 4, 7, 9],
       [8, 9, 9, 4]])

In [71]:
np.sin(arr1)

array([[ 0.6569866 , -0.95892427, -0.7568025 ,  0.41211849],
       [ 0.6569866 , -0.7568025 ,  0.6569866 ,  0.41211849],
       [ 0.98935825,  0.41211849,  0.41211849, -0.7568025 ]])

In [72]:
np.cos(arr1)

array([[ 0.75390225,  0.28366219, -0.65364362, -0.91113026],
       [ 0.75390225, -0.65364362,  0.75390225, -0.91113026],
       [-0.14550003, -0.91113026, -0.91113026, -0.65364362]])

In [73]:
np.log10(arr1)

array([[0.84509804, 0.69897   , 0.60205999, 0.95424251],
       [0.84509804, 0.60205999, 0.84509804, 0.95424251],
       [0.90308999, 0.95424251, 0.95424251, 0.60205999]])

In [75]:
np.power(arr1,3)

array([[343, 125,  64, 729],
       [343,  64, 343, 729],
       [512, 729, 729,  64]], dtype=int32)

In [76]:
np.mean(arr1)

6.833333333333333

In [77]:
np.max(arr1)

9

In [83]:
np.subtract(arr1, arr2)

array([[ 5,  1,  0,  7],
       [-2,  2,  5,  1],
       [ 2,  2,  5, -1]])

In [84]:
np.multiply(arr1, arr2)

array([[14, 20, 16, 18],
       [63,  8, 14, 72],
       [48, 63, 36, 20]])

In [85]:
np.power(arr1, arr2)

array([[      49,      625,      256,       81],
       [40353607,       16,       49, 43046721],
       [  262144,  4782969,     6561,     1024]])

In [87]:
arr1,arr2

(array([[7, 5, 4, 9],
        [7, 4, 7, 9],
        [8, 9, 9, 4]]),
 array([[2, 4, 4, 2],
        [9, 2, 2, 8],
        [6, 7, 4, 5]]))

In [86]:
np.mod(arr1, arr2) # return element wise remainder

array([[1, 1, 0, 1],
       [7, 0, 1, 1],
       [2, 2, 1, 4]])