In [ ]:
import numpy as np 

In [ ]:
arr1 = np.ones((3,4))
arr1

In [ ]:
arr1+5 # adding 5 to each element

In [ ]:
arr1*5

In [ ]:
np.empty((3,4),int) # gives u a random array for the mentioned shape and data type (default is decimal)

In [ ]:
np.eye(3,4,dtype=int) # gives u a random array for the mentioned shape(only rows can be told) and data type (default is decimal)

In [ ]:
arr1

In [ ]:
# optional
import pandas as pd
pd.DataFrame(arr1)

In [ ]:
# extra topics
import random
#random.choice(range(1,100))
random.choice((1,2,3))

In [ ]:
random.randrange(1,1000)

In [ ]:
random.random() # for random number
lis = [1,2,3,4,5]
random.shuffle(lis)
lis

In [64]:
# num py also includes random library
np.random.rand(3,2)

array([[0.31179687, 0.92080836],
       [0.92106422, 0.61147076],
       [0.00725345, 0.16915438]])

In [69]:
np.random.rand(3)

array([0.85233512, 0.3919438 , 0.20188011])

In [71]:
np.random.randn(2,4)

array([[-0.02387178, -1.38345096,  1.44037206,  0.37474405],
       [ 1.91486791,  1.60073435, -0.8263786 ,  1.18080915]])

In [75]:
np.random.random_sample(4)

array([0.30206089, 0.62320605, 0.94931907, 0.99966137])

In [95]:
arr2 = np.random.randint(1,5, size=(3,4))
arr2

array([[1, 2, 2, 4],
       [1, 4, 3, 4],
       [1, 4, 4, 4]])

In [96]:
arr2.size

12

In [97]:
arr2.shape

(3, 4)

In [98]:
arr2.ndim

2

In [104]:
# reshaping of arr based on the array size
arr2.reshape(2,6) # the shape should be multiple of arr size
arr2

array([[1, 2, 2, 4],
       [1, 4, 3, 4],
       [1, 4, 4, 4]])

In [105]:
id(arr2)

2751847212944

In [90]:
arr2.ndim

2

In [102]:
# negative parameter in case if columns are not sure Numpy will take care of that
# at least we should know one dimension either row or column at minimum

In [100]:
arr2.reshape(4,-1) 

array([[1, 2, 2],
       [4, 1, 4],
       [3, 4, 1],
       [4, 4, 4]])

In [108]:
arr3 = arr2.reshape(-4,2)

In [109]:
id(arr2)

2751847212944

In [110]:
id(arr3)

2751847212176

In [111]:
arr2.reshape(-4,2).base

array([[1, 2, 2, 4],
       [1, 4, 3, 4],
       [1, 4, 4, 4]])

In [115]:
arr2.reshape(2, 3, 2)

array([[[1, 2],
        [2, 4],
        [1, 4]],

       [[3, 4],
        [1, 4],
        [4, 4]]])

In [120]:
arr4 = arr2.reshape(3, 2, 2)
arr4

array([[[1, 2],
        [2, 4]],

       [[1, 4],
        [3, 4]],

       [[1, 4],
        [4, 4]]])

In [119]:
arr4.ndim

3

In [125]:
arr5 = np.zeros((3,1,2,3)) # 2 rows 3 columns >> 2d array+1 dimension
arr5

array([[[[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]]]])

In [126]:
arr5.ndim

4

In [127]:
arr5.shape

(3, 1, 2, 3)

In [130]:
arr1 = np.random.randint(1,11,(5,6))
arr1

array([[ 1,  6, 10,  6,  7,  4],
       [ 9,  4,  1,  3,  7,  2],
       [ 9,  3,  4,  1,  4,  7],
       [ 9,  5, 10,  6,  7,  5],
       [ 2,  6,  1,  5,  5,  4]])

In [131]:
arr1 > 5 #  chk for all the elements and chk it values against 5

array([[False,  True,  True,  True,  True, False],
       [ True, False, False, False,  True, False],
       [ True, False, False, False, False,  True],
       [ True, False,  True,  True,  True, False],
       [False,  True, False, False, False, False]])

In [132]:
arr1[arr1>5]

array([ 6, 10,  6,  7,  9,  7,  9,  7,  9, 10,  6,  7,  6])

In [134]:
arr2 = arr1[arr1<5]

In [135]:
arr2

array([1, 4, 4, 1, 3, 2, 3, 4, 1, 4, 2, 1, 4])

In [136]:
arr2[1]

4

In [137]:
arr1

array([[ 1,  6, 10,  6,  7,  4],
       [ 9,  4,  1,  3,  7,  2],
       [ 9,  3,  4,  1,  4,  7],
       [ 9,  5, 10,  6,  7,  5],
       [ 2,  6,  1,  5,  5,  4]])

In [138]:
arr1[0]

array([ 1,  6, 10,  6,  7,  4])

In [140]:
arr1[0][2]

10

In [141]:
arr1[0,[1,3]]

array([6, 6])

In [142]:
arr1

array([[ 1,  6, 10,  6,  7,  4],
       [ 9,  4,  1,  3,  7,  2],
       [ 9,  3,  4,  1,  4,  7],
       [ 9,  5, 10,  6,  7,  5],
       [ 2,  6,  1,  5,  5,  4]])

In [143]:
arr1[2:4]

array([[ 9,  3,  4,  1,  4,  7],
       [ 9,  5, 10,  6,  7,  5]])

In [145]:
arr1[2:4,[1,2,3]]

array([[ 3,  4,  1],
       [ 5, 10,  6]])

In [146]:
arr1[2:4,0:3] # slicing on rows  as first parameter and columns as second parameter

array([[ 9,  3,  4],
       [ 9,  5, 10]])

In [148]:
arr1

array([[ 1,  6, 10,  6,  7,  4],
       [ 9,  4,  1,  3,  7,  2],
       [ 9,  3,  4,  1,  4,  7],
       [ 9,  5, 10,  6,  7,  5],
       [ 2,  6,  1,  5,  5,  4]])

In [149]:
arr1[[1,3]] # row 1 and 3 from arr1

array([[ 9,  4,  1,  3,  7,  2],
       [ 9,  5, 10,  6,  7,  5]])

In [152]:
arr1[[1,3],[0,2]] 

array([ 9, 10])

In [153]:
# matrix multiplication
arr1

array([[ 1,  6, 10,  6,  7,  4],
       [ 9,  4,  1,  3,  7,  2],
       [ 9,  3,  4,  1,  4,  7],
       [ 9,  5, 10,  6,  7,  5],
       [ 2,  6,  1,  5,  5,  4]])

In [157]:
arr2 = np.ones((5,6),dtype=int)
arr2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [159]:
arr2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [160]:
arr2.flatten() # make it one dimension

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [164]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [165]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [166]:
np.sum(arr)

27

In [167]:
np.sum(arr, axis=0)# axis =0 row wise 

array([ 6,  9, 12])

In [168]:
np.sum(arr, axis=1) # axis =1 column wise 

array([ 6, 15,  6])

In [169]:
# expand dimensions
arr = np.array([1,2,3,4])

In [170]:
arr

array([1, 2, 3, 4])

In [171]:
arr.ndim

1

In [172]:
arr1 = np.expand_dims(arr,axis=0)

In [173]:
arr1

array([[1, 2, 3, 4]])

In [174]:
arr1.ndim

2

In [175]:
arr2 = np.expand_dims(arr1,axis=0) # this function increases the dimension by 1

In [178]:
arr2

array([[[1, 2, 3, 4]]])

In [176]:
arr2.ndim

3

In [177]:
arr2.shape

(1, 1, 4)

In [179]:
arr

array([1, 2, 3, 4])

In [180]:
arr1 = np.expand_dims(arr,axis=1)

In [181]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [182]:
arr = np.zeros((3,4))

In [183]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [186]:
arr1 = np.expand_dims(arr,axis=0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [187]:
arr1.ndim

3

In [188]:
arr1 = np.expand_dims(arr,axis=1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [189]:
arr1.ndim

3